configs:
- reproduce_table3/configs/glue_table3/cola_bf16.yaml
- reproduce_table3/configs/glue_table3/cola_lora_bf16.yaml
- reproduce_table3/configs/glue_table3/cola_qlora_int8.yaml
- reproduce_table3/configs/glue_table3/cola_qlora_fp4.yaml
- reproduce_table3/configs/glue_table3/sst2_bf16.yaml
- reproduce_table3/configs/glue_table3/sst2_lora_bf16.yaml
- reproduce_table3/configs/glue_table3/sst2_qlora_int8.yaml
- reproduce_table3/configs/glue_table3/sst2_qlora_fp4.yaml
- reproduce_table3/configs/glue_table3/mrpc_bf16.yaml
- reproduce_table3/configs/glue_table3/mrpc_lora_bf16.yaml
- reproduce_table3/configs/glue_table3/mrpc_qlora_int8.yaml
- reproduce_table3/configs/glue_table3/mrpc_qlora_fp4.yaml
- reproduce_table3/configs/glue_table3/qqp_bf16.yaml
- reproduce_table3/configs/glue_table3/qqp_lora_bf16.yaml
- reproduce_table3/configs/glue_table3/qqp_qlora_int8.yaml
- reproduce_table3/configs/glue_table3/qqp_qlora_fp4.yaml
- reproduce_table3/configs/glue_table3/stsb_bf16.yaml
- reproduce_table3/configs/glue_table3/stsb_lora_bf16.yaml
- reproduce_table3/configs/glue_table3/stsb_qlora_int8.yaml
- reproduce_table3/configs/glue_table3/stsb_qlora_fp4.yaml
- reproduce_table3/configs/glue_table3/mnli_bf16.yaml
- reproduce_table3/configs/glue_table3/mnli_lora_bf16.yaml
- reproduce_table3/configs/glue_table3/mnli_qlora_int8.yaml
- reproduce_table3/configs/glue_table3/mnli_qlora_fp4.yaml
- reproduce_table3/configs/glue_table3/qnli_bf16.yaml
- reproduce_table3/configs/glue_table3/qnli_lora_bf16.yaml
- reproduce_table3/configs/glue_table3/qnli_qlora_int8.yaml
- reproduce_table3/configs/glue_table3/qnli_qlora_fp4.yaml
- reproduce_table3/configs/glue_table3/rte_bf16.yaml
- reproduce_table3/configs/glue_table3/rte_lora_bf16.yaml
- reproduce_table3/configs/glue_table3/rte_qlora_int8.yaml
- reproduce_table3/configs/glue_table3/rte_qlora_fp4.yaml
