configs:
- reproduce_table3/configs/table3_full/t5_80m_bf16.yaml
- reproduce_table3/configs/table3_full/t5_80m_bf16_replication.yaml
- reproduce_table3/configs/table3_full/t5_80m_lora_bf16.yaml
- reproduce_table3/configs/table3_full/t5_80m_qlora_int8.yaml
- reproduce_table3/configs/table3_full/t5_80m_qlora_fp4.yaml
- reproduce_table3/configs/table3_full/t5_80m_qlora_nf4_dq.yaml
- reproduce_table3/configs/table3_full/t5_250m_bf16.yaml
- reproduce_table3/configs/table3_full/t5_250m_bf16_replication.yaml
- reproduce_table3/configs/table3_full/t5_250m_lora_bf16.yaml
- reproduce_table3/configs/table3_full/t5_250m_qlora_int8.yaml
- reproduce_table3/configs/table3_full/t5_250m_qlora_fp4.yaml
- reproduce_table3/configs/table3_full/t5_250m_qlora_nf4_dq.yaml
- reproduce_table3/configs/table3_full/t5_780m_bf16.yaml
- reproduce_table3/configs/table3_full/t5_780m_bf16_replication.yaml
- reproduce_table3/configs/table3_full/t5_780m_lora_bf16.yaml
- reproduce_table3/configs/table3_full/t5_780m_qlora_int8.yaml
- reproduce_table3/configs/table3_full/t5_780m_qlora_fp4.yaml
- reproduce_table3/configs/table3_full/t5_780m_qlora_nf4_dq.yaml
- reproduce_table3/configs/table3_full/t5_3b_bf16.yaml
- reproduce_table3/configs/table3_full/t5_3b_bf16_replication.yaml
- reproduce_table3/configs/table3_full/t5_3b_lora_bf16.yaml
- reproduce_table3/configs/table3_full/t5_3b_qlora_int8.yaml
- reproduce_table3/configs/table3_full/t5_3b_qlora_fp4.yaml
- reproduce_table3/configs/table3_full/t5_3b_qlora_nf4_dq.yaml
- reproduce_table3/configs/table3_full/t5_11b_bf16.yaml
- reproduce_table3/configs/table3_full/t5_11b_bf16_replication.yaml
- reproduce_table3/configs/table3_full/t5_11b_lora_bf16.yaml
- reproduce_table3/configs/table3_full/t5_11b_qlora_int8.yaml
- reproduce_table3/configs/table3_full/t5_11b_qlora_fp4.yaml
- reproduce_table3/configs/table3_full/t5_11b_qlora_nf4_dq.yaml
- reproduce_table3/configs/table3_full/roberta_large_sst2_bf16.yaml
- reproduce_table3/configs/table3_full/roberta_large_sst2_bf16_replication.yaml
- reproduce_table3/configs/table3_full/roberta_large_sst2_lora_bf16.yaml
- reproduce_table3/configs/table3_full/roberta_large_sst2_qlora_int8.yaml
- reproduce_table3/configs/table3_full/roberta_large_sst2_qlora_fp4.yaml
